#!/bin/sh
# This wrapper provides automatic reloading on file modifications
# to the pdfviewer mupdf via inotify.
# Needs mupdf and inotify-tools

# Prepare parameters.
cd "$(dirname "$1")"
pdf=$(basename "$1")
shift
passthrough="$@"

# Return with an error if the given file does not exist.
if [ ! -e $pdf ]; then
    echo "$pdf: No such file or directory"
    exit 1
fi

# Start mupdf with the given file.
mupdf $pdf $passthrough &

# Track the PID of the mupdf instance.
pid_mupdf=$!

# Kill the mupdf instance if the shell script terminates.
trap "kill ${pid_mupdf}" SIGINT SIGTERM SIGQUIT SIGKILL

# Watch for changes in the directory of the given file. This is necessary
# to recieve events after the file was deleted.
inotifywait -m -e close_write "$PWD" -q --format "%f"| while read file; do
    # Only refresh on events of the file in question and if this file exists.
    if [ "$file" = "$pdf" ] && [ -e "$pdf" ]; then
        kill -HUP $pid_mupdf
    fi
done &

# If mupdf terminates kill the inotifywait process.
wait $pid_mupdf
pkill -P $$
cd - > /dev/null
