#!/bin/bash
source ~/comfy_guration/scripts/manager/utils.sh

# dependencies
sudo pacman --needed --noconfirm -S man-db most zsh rofi rofi-emoji xdotool kitty tree polybar feh nodejs npm ripgrep go luarocks stylua lazygit yazi picom ttf-hack-nerd noto-fonts-emoji zsh-syntax-highlighting fd pamixer dunst network-manager-applet maim nemo python-pipx pyenv wget ruby downgrade

# OMY Dependency
downgrade 'ruby-json=2.6.3-1'

paru --needed -S i3lock-color pyenv-virtualenv

u_safe_mkdir ~/.npm-global
u_safe_mkdir ~/pictures
u_safe_mkdir ~/pictures/screenshots

# move in another file
chsh -s $(which zsh)
# oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
