#!/bin/bash

sudo pacman --needed --noconfirm -S xorg-xbacklight xf86-video-intel

sudo pacman --needed --noconfirm -S tlp tlp-rdw powertop acpi acpi_call
sudo systemctl enable tlp
sudo systemctl mask systemd-rfkill.socket
sudo systemctl mask systemd-rfkill.service
