#!/bin/bash
# This script was made to easily install the minimum required to clone this repository
# and run the other scripts. You shouldn't use it.

#Reflector
sudo pacman -Syu
sudo pacman --needed -S reflector
sudo reflector --latest 5 --sort rate --save /etc/pacman.d/mirrorlist
sudo systemctl enable reflector.service

#Paru
sudo pacman  --needed base-devel
git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -si
cd ..
rm -rf paru

#Graphics + chrome
sudo pacman --needed -S xorg-server xorg-apps xorg-xinit xterm xclip i3-gaps i3blocks numlockx ttf-dejavu-nerd
echo 'exec i3' > ~/.xinitrc
paru -S google-chrome

#SSH
sudo pacman --needed -S openssh
ssh-keygen -t rsa
cat ~/.ssh/id_rsa.pub | xclip -selection clipboard

echo "Now it's time to startx and insert the new SSH key in github to clone the repository"
